version: '3.8'

services:
  # Base de datos PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: plataforma-tramites-db
    environment:
      POSTGRES_DB: plataforma_tramites_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Super2050*
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d
    networks:
      - tramites-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Aplicación Spring Boot
  app:
    build: .
    container_name: plataforma-tramites-app
    environment:
      # Base de datos
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/plataforma_tramites_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Super2050*

      # JWT
      JWT_SECRET: mySecretKey12345678901234567890123456789012345678901234567890

      # Email (configurar con valores reales para producción)
      SMTP_HOST: smtp.gmail.com
      SMTP_PORT: 587
      SMTP_USERNAME: test@example.com
      SMTP_PASSWORD: testpassword

      # Notificaciones
      NOTIFICATIONS_ENABLED: true
      NOTIFICATIONS_FROM_EMAIL: noreply@plataforma-tramites.gov.co
      NOTIFICATIONS_FROM_NAME: Plataforma de Trámites
      BASE_URL: http://localhost:8080

      # Documentos
      DOCUMENTS_STORAGE_PATH: /app/storage/documents
      DOCUMENTS_MAX_FILE_SIZE: 50MB
      DOCUMENTS_MAX_REQUEST_SIZE: 100MB

      # Perfil de Spring
      SPRING_PROFILES_ACTIVE: production
    ports:
      - "8080:8080"
    volumes:
      - app_storage:/app/storage
      - app_logs:/app/logs
    networks:
      - tramites-network
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  tramites-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
  app_storage:
    driver: local
  app_logs:
    driver: local